### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by DarkCat09** [DarkCat09/python-aternos#75]
- [ ] **Fix detection by Aternos** (see https://github.com/DarkCat09/python-aternos/issues/75#issuecomment-1572125741 and #85)
- [x] Create a `BASE_URL` constant in each module and use it to generate URLs, change `/panel/ajax` to `/ajax` (fixes #74)
- [x] Parse a server page instead of requesting `/panel/ajax/status.php` to get lastStatus object (fixes #74)
- [x] Fix 400 Bad Request
- [x] `from_credentials` -> instantiating AternosClient, configuring, calling `login()`
- [x] Patially rewrite `atclient`, move some methods into `ataccount`
- [x] When the previous task is done, we can set captcha solvers API key directly through `atconn.session.captcha` and, after that, call any endpoints including `login()` (fixes #62)
- [x] `getLogger` in log.py instead of calling `logging` methods, create a `debug` field in AternosClient to configure debug logging
- [ ] Automatically parse the server page to get lastStatus object if `AternosClient.autoparse` is set to true
- [ ] Parse pages asynchronously where possible
- [x] Generate SEC token like Aternos does: 11 random symbols (alphanumeric) + 5 zeroes
- [ ] Change the error code for unaccepted EULA, rewrite ServerStartError (fixes #79)
- [ ] Fully rewrite AternosWss, I should finally understand how AsyncIO works and simplify the atwss logic (fixes #69, #68)
- [ ] Update unit tests, setup CI/CD on GitHub, build and upload to PyPI on pushing to `release` branch (not `main`)
- [ ] Update documentation

**Comment by MedCodeHack** [comment]
pls, i still got the 503 server error

**Comment by Emeteil** [comment]
![image](https://github.com/DarkCat09/python-aternos/assets/94739287/30b88304-3150-46bc-a0cc-72672c1effdc)
Perhaps the problem is with me personally, but I have this error both on the server and on the main PC. Perhaps the parsing libraries are outdated.

**Comment by MedCodeHack** [comment]
> ![image](https://user-images.githubusercontent.com/94739287/240706043-30b88304-3150-46bc-a0cc-72672c1effdc.png) Perhaps the problem is with me personally, but I have this error both on the server and on the main PC. Perhaps the parsing libraries are outdated. Maybe I'm in a hurry, and not everything is finished yet. Then I apologize.

I have the same error i tried to reinstall the library so the library is updated but still got the same error!

**Comment by Varo1234** [comment]
With the new files you uploaded, I got this error now, I didn't use the library from pip, I downloaded your files and used them.


![image](https://github.com/DarkCat09/python-aternos/assets/51148348/0401a81e-fc3b-4c62-ace8-c9e8f4fe6fa5)

By the way, thank you very much for supporting and updating the library.

**Comment by DarkCat09** [comment]
@Emeteil, @MedCodeHack, @Varo1234,

Please, wait for `v3.0.0` release. I know, the problem still exists for now.

**Comment by DarkCat09** [comment]
@Emeteil, @MedCodeHack, @Varo1234,

it works!

**Comment by Varo1234** [comment]
### Your account has been permanently suspended.
### Reason: Automating access to our website (TOS §5.2e) 

only 5 hours after updating the bot

:(

**Comment by Emeteil** [comment]
> ### Your account has been permanently suspended.
> ### Reason: Automating access to our website (TOS §5.2e)
> only 5 hours after updating the bot
> 
> :(

I have the same. On all 3 accounts (2 were connected to the python script, and 3 just had access to all servers). Strange though, since I only ran two servers at the same time once after updating the library. I take it aternos changed the authorization link on purpose to ban accounts. Sad, but we knew what we were doing using unofficial API)

**Comment by DarkCat09** [comment]
> Im curious how do they detect that? My first suspection was that some guys reports that to aternos but i don't think so..

@Varo1234, @Emeteil, @Miloldr,

I think they detect it by unusual requests, some Python-specific headers/cookies, or library bugs in generating tokens...  
It would be great if you could help with checking original JavaScript code and updating python-aternos.

**Comment by Supslike** [comment]
any update on the progress?

**Comment by DarkCat09** [comment]
> any update on the progress?

@Supslike, maybe tomorrow... I'll try to fix detection of automated requests, and then continue code refactoring and APIs updating.
